stages:
  split_data:
    cmd: python dvc_demo/code/split_data.py --input dvc_demo/data/data.csv --output dvc_demo/data/processed --test-size 0.2 --random-state 42
    deps:
    - dvc_demo/data/data.csv
    - dvc_demo/code/split_data.py
    outs:
    - dvc_demo/data/processed/train.csv
    - dvc_demo/data/processed/test.csv

  data_statistics:
    cmd: python dvc_demo/code/data_statistics.py --train dvc_demo/data/processed/train.csv --output dvc_demo/reports/statistics
    deps:
    - dvc_demo/data/processed/train.csv
    - dvc_demo/code/data_statistics.py
    outs:
    - dvc_demo/reports/statistics/statistics.json
    - dvc_demo/reports/statistics/class_distribution.png
    - dvc_demo/reports/statistics/correlation_heatmap.png
    - dvc_demo/reports/statistics/feature_distributions.png
    - dvc_demo/reports/statistics/pairplot_key_features.png
    - dvc_demo/reports/statistics/feature_variance.png
    - dvc_demo/reports/statistics/summary_statistics.csv

  train_model:
    cmd: python dvc_demo/code/train_model.py --train dvc_demo/data/processed/train.csv --test dvc_demo/data/processed/test.csv --output dvc_demo/models --n-estimators 100 --random-state 42
    deps:
    - dvc_demo/data/processed/train.csv
    - dvc_demo/data/processed/test.csv
    - dvc_demo/code/train_model.py
    outs:
    - dvc_demo/models/random_forest_model.joblib
    - dvc_demo/models/scaler.joblib
    - dvc_demo/models/feature_importance.csv
    - dvc_demo/models/confusion_matrix.png
    - dvc_demo/models/roc_curve.png
    - dvc_demo/models/feature_importance.png
    - dvc_demo/models/prediction_analysis.png
    metrics:
    - dvc_demo/models/metrics.json 