stages:
  split_data:
    cmd: python code/split_data.py --input data/raw/data.csv --output data/processed --test-size 0.2 --random-state 42
    deps:
    - data/raw/data.csv
    - code/split_data.py
    outs:
    - data/processed/train.csv
    - data/processed/test.csv

  compute_data_statistics:
    cmd: python code/data_statistics.py --train data/processed/train.csv --output data/reports/statistics
    deps:
    - data/processed/train.csv
    - code/data_statistics.py
    outs:
    - data/reports/statistics/statistics.json
    - data/reports/statistics/class_distribution.png
    - data/reports/statistics/correlation_heatmap.png
    - data/reports/statistics/feature_distributions.png
    - data/reports/statistics/pairplot_key_features.png
    - data/reports/statistics/feature_variance.png
    - data/reports/statistics/summary_statistics.csv

  train_model:
    cmd: python code/train_model.py --train data/processed/train.csv --test data/processed/test.csv --output data/models --n-estimators 100 --random-state 42
    deps:
    - data/processed/train.csv
    - data/processed/test.csv
    - code/train_model.py
    outs:
    - data/models/random_forest_model.joblib
    - data/models/scaler.joblib
    - data/models/feature_importance.csv
    - data/models/confusion_matrix.png
    - data/models/roc_curve.png
    - data/models/feature_importance.png
    - data/models/prediction_analysis.png
    metrics:
    - data/models/metrics.json 