stages:
  split_data:
    cmd: >-
      python code/split_data.py 
      --input data/raw/data.csv 
      --output data/processed
    deps:
    - data/raw/data.csv
    - code/split_data.py
    params:
    - split_data.test_size
    - split_data.random_state
    outs:
    - data/processed/train.csv
    - data/processed/test.csv

  compute_data_statistics:
    foreach:
      - train
      - test
    do:
      cmd: >-
        python code/data_statistics.py 
        --train data/processed/${item}.csv 
        --output data/reports/statistics/${item}
      deps:
      - data/processed/${item}.csv
      - code/data_statistics.py
      params:
      - data_statistics.important_features
      - data_statistics.pairplot_features
      - data_statistics.top_variance_features
      outs:
      - data/reports/statistics/${item}/statistics.json
      - data/reports/statistics/${item}/class_distribution.png
      - data/reports/statistics/${item}/correlation_heatmap.png
      - data/reports/statistics/${item}/feature_distributions.png
      - data/reports/statistics/${item}/pairplot_key_features.png
      - data/reports/statistics/${item}/feature_variance.png
      - data/reports/statistics/${item}/summary_statistics.csv

  train_model:
    cmd: >-
      python code/train_model.py 
      --train data/processed/train.csv 
      --test data/processed/test.csv 
      --output data/models
    deps:
    - data/processed/train.csv
    - data/processed/test.csv
    - code/train_model.py
    params:
    - train_model.n_estimators
    - train_model.max_depth
    - train_model.min_samples_split
    - train_model.min_samples_leaf
    - train_model.max_features
    - train_model.bootstrap
    - train_model.random_state
    - train_model.pos_label
    - train_model.use_feature_scaling
    - train_model.top_features_to_plot
    outs:
    - data/models/random_forest_model.joblib
    - data/models/scaler.joblib
    - data/models/feature_importance.csv
    - data/models/confusion_matrix.png
    - data/models/roc_curve.png
    - data/models/feature_importance.png
    - data/models/prediction_analysis.png
    metrics:
    - data/models/metrics.json 