# DVC Pipeline Parameters Configuration
# This file contains all configurable parameters for the breast cancer classification pipeline

split_data:
  test_size: 0.2
  random_state: 42

train_model:
  # Random Forest hyperparameters
  n_estimators: 1          # Number of trees in the forest
  max_depth: 1             # Maximum depth of trees (null for unlimited)
  min_samples_split: 2     # Minimum samples required to split an internal node
  min_samples_leaf: 1      # Minimum samples required to be at a leaf node
  max_features: "sqrt"     # Number of features to consider for best split
  bootstrap: true          # Whether bootstrap samples are used when building trees
  random_state: 42         # Random seed for reproducibility
  n_jobs: 2              # Number of jobs to run in parallel (-1 uses all processors)
  
  # Model training parameters
  pos_label: "M"          # Positive class label for binary classification metrics
  
  # Feature selection and preprocessing
  use_feature_scaling: true     # Whether to apply StandardScaler

evaluate_model:
  # Model evaluation parameters
  pos_label: "M"          # Positive class label for binary classification metrics
  
  # Visualization parameters
  top_features_to_plot: 20      # Number of top features to show in importance plot